version: "3.9"

services:

  api:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: uptime-api
    ports:
      - "8000:8000"
    environment:
      - MONITORS_TABLE=uptime-monitors
      - CHECKS_TABLE=uptime-checks
      - AWS_REGION=us-east-1
      - LOCAL_DYNAMO_URL=http://dynamodb-local:8001
      - LOCAL_MODE=true
      - CHECK_INTERVAL_MINUTES=1      # every 1 min locally so you see results fast
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
    depends_on:
      - dynamodb-local
    volumes:
      - ./app:/home/appuser/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - uptime-net

  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: uptime-dynamodb
    ports:
      - "8001:8001"
    command: "-jar DynamoDBLocal.jar -sharedDb -port 8001"
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/localhost/8001 && echo -e 'GET / HTTP/1.0\\r\\n' >&3 && cat <&3 | grep -q 'HTTP' && exit 0 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - uptime-net

networks:
  uptime-net:
    driver: bridge
