apiVersion: 1

datasources:
  - name: CloudWatch
    type: cloudwatch
    access: proxy
    uid: cloudwatch-ds
    isDefault: true
    jsonData:
      authType: default          # uses ECS task IAM role in prod; env vars in local dev
      defaultRegion: us-east-1
      logsTimeout: 30s
    version: 1
    editable: false
